# Docker Compose para desarrollo local
version: '3.8'

services:
  clickup-forms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: clickup-forms-app
    restart: unless-stopped
    
  # Opcional: Nginx proxy si necesitas SSL o múltiples servicios
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - clickup-forms
