import { Category } from '../models/interfaces';

export const CATEGORIES: Category[] = [
  {
    id: 'bugs',
    name: 'Bugs',
    description: 'Reportar errores y problemas técnicos',
    icon: 'bug',
    image: '/assets/img/categories/bugs.png',
    color: 'from-red-600 to-red-700',
    allowedRoles: ['riesgo', 'atc', 'soporte'],
    systems: [
      {
        id: 'sorti-ec',
        name: 'Sorti.ec',
        description: 'Sistema de apuestas de Sorti',
        formUrl: '',
        image: '/assets/img/systems/sorti-ec.png',
        color: 'from-blue-600 to-blue-700',
        //añadir los permisos de cada rol despues que riden te de como va
        allowedRoles: ['riesgo', 'atc', 'soporte', 'marketing'],
      },
      {
        id: 'sorticenter',
        name: 'SortiCenter',
        description: 'Sistema de gestión',
        formUrl: '',
        image: '/assets/img/systems/sorti-center.png',
        color: 'from-orange-600 to-orange-700',
        allowedRoles: ['riesgo', 'atc', 'soporte', 'marketing'],
      },
      {
        id: 'backoffice',
        name: 'BackOffice',
        description: 'Panel de administración',
        formUrl: '',
        image: '/assets/img/systems/backoffice.png',
        color: 'from-gray-600 to-gray-700',
        allowedRoles: ['riesgo', 'atc', 'soporte', 'marketing'],
      },
      {
        id: 'contabilidad',
        name: 'Contabilidad',
        description: 'Sistema contable',
        formUrl: '',
        image: '/assets/img/systems/contabilidad.png',
        color: 'from-emerald-600 to-emerald-700',
        allowedRoles: ['atc', 'soporte', 'marketing'], // Oculto para riesgo
      },
      {
        id: 'growth-hacking',
        name: 'Growth Hacking',
        description: 'Herramientas de crecimiento',
        formUrl: '',
        image: '/assets/img/systems/growth-hacking.png',
        color: 'from-violet-600 to-violet-700',
        allowedRoles: ['atc', 'soporte', 'marketing'], // Oculto para riesgo
      },
    ],
  },
  {
    id: 'mejoras',
    name: 'Mejoras o Requerimientos de Cambio',
    description: 'Solicitudes de mejoras y nuevas funcionalidades',
    icon: 'improvements',
    image: '/assets/img/categories/mejoras.png',
    color: 'from-blue-600 to-blue-700',
    allowedRoles: ['riesgo', 'atc', 'soporte', 'marketing'],
    systems: [
      {
        id: 'sorti-ec',
        name: 'Sorti.ec',
        description: 'Sistema de apuestas de Sorti',
        formUrl: '',
        image: '/assets/img/systems/sorti-ec.png',
        color: 'from-blue-600 to-blue-700',
        allowedRoles: ['riesgo', 'atc', 'soporte', 'marketing'],
      },
      {
        id: 'sorticenter',
        name: 'SortiCenter',
        description: 'Sistema de gestión',
        formUrl: '',
        image: '/assets/img/systems/sorti-center.png',
        color: 'from-orange-600 to-orange-700',
      },
      {
        id: 'backoffice',
        name: 'BackOffice',
        description: 'Panel de administración',
        formUrl: '',
        image: '/assets/img/systems/backoffice.png',
        color: 'from-gray-600 to-gray-700',
      },
      {
        id: 'contabilidad',
        name: 'Contabilidad',
        description: 'Sistema contable',
        formUrl: '',
        image: '/assets/img/systems/contabilidad.png',
        color: 'from-emerald-600 to-emerald-700',
      },
      {
        id: 'growth-hacking',
        name: 'Growth Hacking',
        description: 'Herramientas de crecimiento',
        formUrl: '',
        image: '/assets/img/systems/growth-hacking.png',
        color: 'from-violet-600 to-violet-700',
      },
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing y Contenido',
    description: 'Estrategias de marketing y gestión de contenido',
    icon: 'marketing',
    image: '/assets/img/categories/marketing.png',
    color: 'from-pink-600 to-pink-700',
    allowedRoles: ['marketing'],
    systems: [
      {
        id: 'sorti-ec',
        name: 'Sorti.ec',
        description: 'Sistema de apuestas de Sorti',
        formUrl: '',
        image: '/assets/img/systems/sorti-ec.png',
        color: 'from-blue-600 to-blue-700',
      },
      {
        id: 'sorticenter',
        name: 'SortiCenter',
        description: 'Sistema de gestión',
        formUrl: '',
        image: '/assets/img/systems/sorti-center.png',
        color: 'from-orange-600 to-orange-700',
      },
      {
        id: 'backoffice',
        name: 'BackOffice',
        description: 'Panel de administración',
        formUrl: '',
        image: '/assets/img/systems/backoffice.png',
        color: 'from-gray-600 to-gray-700',
      },
      {
        id: 'contabilidad',
        name: 'Contabilidad',
        description: 'Sistema contable',
        formUrl: '',
        image: '/assets/img/systems/contabilidad.png',
        color: 'from-emerald-600 to-emerald-700',
      },
      {
        id: 'growth-hacking',
        name: 'Growth Hacking',
        description: 'Herramientas de crecimiento',
        formUrl: '',
        image: '/assets/img/systems/growth-hacking.png',
        color: 'from-violet-600 to-violet-700',
      },
    ],
  },
  {
    id: 'riesgo',
    name: 'Riesgo',
    description: 'Gestión de riesgos y seguridad',
    icon: 'shield',
    image: '/assets/img/categories/riesgo.png',
    color: 'from-amber-600 to-amber-700',
    allowedRoles: ['riesgo'],
    systems: [
      {
        id: 'sorti-ec',
        name: 'Sorti.ec',
        description: 'Sistema de apuestas de Sorti',
        formUrl: '',
        image: '/assets/img/systems/sorti-ec.png',
        color: 'from-blue-600 to-blue-700',
      },
      {
        id: 'sorticenter',
        name: 'SortiCenter',
        description: 'Sistema de gestión',
        formUrl: '',
        image: '/assets/img/systems/sorti-center.png',
        color: 'from-orange-600 to-orange-700',
      },
      {
        id: 'backoffice',
        name: 'BackOffice',
        description: 'Panel de administración',
        formUrl: '',
        image: '/assets/img/systems/backoffice.png',
        color: 'from-gray-600 to-gray-700',
      },
      {
        id: 'contabilidad',
        name: 'Contabilidad',
        description: 'Sistema contable',
        formUrl: '',
        image: '/assets/img/systems/contabilidad.png',
        color: 'from-emerald-600 to-emerald-700',
      },
      {
        id: 'growth-hacking',
        name: 'Growth Hacking',
        description: 'Herramientas de crecimiento',
        formUrl: '',
        image: '/assets/img/systems/growth-hacking.png',
        color: 'from-violet-600 to-violet-700',
      },
    ],
  },
  {
    id: 'soporte',
    name: 'Soporte Administrativo',
    description: 'Asistencia y soporte para procesos administrativos',
    icon: 'support',
    image: '/assets/img/categories/soporte.png',
    color: 'from-teal-600 to-teal-700',
    allowedRoles: ['riesgo', 'atc', 'soporte', 'marketing'],
    systems: [
      {
        id: 'sorti-ec',
        name: 'Sorti.ec',
        description: 'Sistema de apuestas de Sorti',
        formUrl: '',
        image: '/assets/img/systems/sorti-ec.png',
        color: 'from-blue-600 to-blue-700',
      },
      {
        id: 'sorticenter',
        name: 'SortiCenter',
        description: 'Sistema de gestión',
        formUrl: '',
        image: '/assets/img/systems/sorti-center.png',
        color: 'from-orange-600 to-orange-700',
      },
      {
        id: 'backoffice',
        name: 'BackOffice',
        description: 'Panel de administración',
        formUrl: '',
        image: '/assets/img/systems/backoffice.png',
        color: 'from-gray-600 to-gray-700',
      },
      {
        id: 'contabilidad',
        name: 'Contabilidad',
        description: 'Sistema contable',
        formUrl: '',
        image: '/assets/img/systems/contabilidad.png',
        color: 'from-emerald-600 to-emerald-700',
      },
      {
        id: 'growth-hacking',
        name: 'Growth Hacking',
        description: 'Herramientas de crecimiento',
        formUrl: '',
        image: '/assets/img/systems/growth-hacking.png',
        color: 'from-violet-600 to-violet-700',
      },
    ],
  },
];
